// Compiled into SXMPlayer.Client (not SXMPlayer.Proxy, where the rest of our
// additions live) because a partial type cannot be extended across assembly
// boundaries — Decorations is declared in SXMPlayer.Client/Client.cs, so the
// other half has to be in that same project.
//
// Why this is needed at all: SiriusXM returns decorations.genre on every
// channel, but the generated Decorations record doesn't map it. That client was
// generated by NSwag from an OpenAPI spec inferred from a HAR capture, so any
// field that happened not to appear in those captured responses is simply
// missing from the model — genre among them.
//
// Adding it here rather than regenerating the client keeps the upstream
// checkout pristine. System.Text.Json populates it from the same payload that
// was already being parsed, so this costs no extra request.
//
// Genre is what makes 434 channels browsable instead of a search box you have
// to already know the answer for.

namespace SXMPlayer
{
    public partial record Decorations
    {
        [System.Text.Json.Serialization.JsonPropertyName("genre")]
        public string? Genre { get; set; }
    }
}
